from django.urls import path
from GestionPrestamo import views
from GestionPrestamo import models
from django.conf.urls.static import static

urlpatterns = [
    path('index',views.Inicio.as_view(),name='index'),
    path('busquedaLibro',views.busquedaLibro,name='busquedaLibro'),
    path('administracion',views.Administracion.as_view(),name='administracion'),
    path('gestionLibro',views.GestionLibro.as_view(),name='gestionLibro'),
    path('gestionUsuario',views.GestionUsuario.as_view(),name='gestionUsuario'),
    path('gestionBibliotecario',views.GestionBibliotecario.as_view(),name='gestionBibliotecario'),
    path('gestionReservacion',views.GestionReservacion.as_view(),name='gestionReservacion'),
    path('gestionEditorial',views.GestionEditorial.as_view(),name='gestionEditorial'),
    path('gestionLibroInstancia',views.GestionLibroInstancia.as_view(),name='gestionLibroInstancia'),
    path('gestionIdioma',views.GestionIdioma.as_view(),name='gestionIdioma'),
    path('gestionEtiquetaLibro',views.GestionEtiquetaLibro.as_view(),name='gestionEtiquetaLibro'),
    path('gestionTipoUsuario',views.GestionTipoUsuario.as_view(),name='gestionTipoUsuario'),
    path('gestionGeneroLibro',views.GestionGeneroLibro.as_view(),name='gestionGeneroLibro'),
    path('gestionAutorLibro',views.GestionAutorLibro.as_view(),name='gestionAutorLibro'),
    path('gestionPais',views.GestionPais.as_view(),name='gestionPais'),
    path('gestionRating',views.GestionRating.as_view(),name='gestionRating'),
    path('gracias',views.Gracias.as_view(),name='gracias'),
    path('registrarLibro',views.RegistrarLibro.as_view(),name='registrarLibro'),
    path('modificarLibro/<int:pk>',views.ModificarLibro.as_view(),name='modificarLibro'),
    path('eliminarLibro/<int:idLibro>',views.eliminarLibro,name='eliminarLibro'),
    path('registrarUsuario/',views.registrarUsuario,name='registrarUsuario'),
    path('modificarUsuario/<int:id>',views.modificarUsuario,name='modificarUsuario'),
    path('eliminarUsuario/<int:id>',views.eliminarUsuario,name='eliminarUsuario'),
    path('registrarBibliotecario/',views.registrarBibliotecario,name='registrarBibliotecario'),
    path('modificarBibliotecario/<int:idBibliotecario>',views.modificarBibliotecario,name='modificarBibliotecario'),
    path('eliminarBibliotecario/<int:idBibliotecario>',views.eliminarBibliotecario,name='eliminarBibliotecario'),
    path('buscar_libro/',views.buscar_libro, name='buscar_libro'),
    path('registrarEtiquetaLibro/',views.registrarEtiquetaLibro, name='registrarEtiquetaLibro'),
    path('modificarEtiquetaLibro/<int:idEtiquetaLibro>',views.modificarEtiquetaLibro,name='modificarEtiquetaLibro'),
    path('eliminarEtiquetaLibro/<int:idEtiquetaLibro>',views.eliminarEtiquetaLibro,name='eliminarEtiquetaLibro'),
    path('registrarEditorial/',views.registrarEditorial, name='registrarEditorial'),
    path('modificarEditorial/<int:idEditorial>',views.modificarEditorial,name='modificarEditorial'),
    path('eliminarEditorial/<int:idEditorial>',views.eliminarEditorial,name='eliminarEditorial'),
    path('registrarReservacion/',views.registrarReservacion, name='registrarReservacion'),
    path('modificarReservacion/<int:idReservacion>',views.modificarReservacion,name='modificarReservacion'),
    path('eliminarReservacion/<int:idReservacion>',views.eliminarReservacion,name='eliminarReservacion'),
    path('registrarIdioma/',views.registrarIdioma, name='registrarIdioma'),
    path('modificarIdioma/<int:idIdioma>',views.modificarIdioma,name='modificarIdioma'),
    path('eliminarIdioma/<int:idIdioma>',views.eliminarIdioma,name='eliminarIdioma'),
    path('registrarLibroInstancia/',views.registrarLibroInstancia, name='registrarLibroInstancia'),
    path('modificarLibroInstancia/<int:idLibroInstancia>',views.modificarLibroInstancia,name='modificarLibroInstancia'),
    path('eliminarLibroInstancia/<int:idLibroInstancia>',views.eliminarLibroInstancia,name='eliminarLibroInstancia'),
    path('registrarTipoUsuario/',views.registrarTipoUsuario, name='registrarTipoUsuario'),
    path('modificarTipoUsuario/<int:idTipoUsuario>',views.modificarTipoUsuario,name='modificarTipoUsuario'),
    path('eliminarTipoUsuario/<int:idTipoUsuario>',views.eliminarTipoUsuario,name='eliminarTipoUsuario'),
    path('registrarGeneroLibro/',views.registrarGeneroLibro, name='registrarGeneroLibro'),
    path('modificarGeneroLibro/<int:idGeneroLibro>',views.modificarGeneroLibro,name='modificarGeneroLibro'),
    path('eliminarGeneroLibro/<int:idGeneroLibro>',views.eliminarGeneroLibro,name='eliminarGeneroLibro'),
    path('registrarAutorLibro/',views.registrarAutorLibro, name='registrarAutorLibro'),
    path('modificarAutorLibro/<int:idAutorLibro>',views.modificarAutorLibro,name='modificarAutorLibro'),
    path('eliminarAutorLibro/<int:idAutorLibro>',views.eliminarAutorLibro,name='eliminarAutorLibro'),
    path('registrarPais/',views.registrarPais, name='registrarPais'),
    path('modificarPais/<int:idPais>',views.modificarPais,name='modificarPais'),
    path('eliminarPais/<int:idPais>',views.eliminarPais,name='eliminarPais'),
    path('registrarRating/<int:idLibro>',views.registrarRating, name='registrarRating'),
    path('modificarRating/<int:id>',views.modificarRating,name='modificarRating'),
    path('eliminarRating/<int:id>',views.eliminarRating,name='eliminarRating'),
    path('GestionReservacionUsuario',views.GestionReservacionUsuario.as_view(),name='GestionReservacionUsuario'),
]
