# Generated by Django 3.0.7 on 2020-07-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPrestamo', '0003_remove_reservacion_lector_reservacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='generoLibro',
            new_name='genero_Libro',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='paisLibro',
            new_name='pais_Libro',
        ),
    ]
