# Generated by Django 3.0.7 on 2020-07-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPrestamo', '0006_auto_20200708_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tituloLibro',
            field=models.CharField(help_text='Ingrese el nombre del Libro', max_length=200, unique=True, verbose_name='Titulo'),
        ),
    ]
