# Generated by Django 3.0.7 on 2020-07-14 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPrestamo', '0007_auto_20200708_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellasRating', models.IntegerField(verbose_name='Valoracion')),
                ('fechaCreacionRating', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estadoRating', models.BooleanField(default=True, verbose_name='Activo')),
                ('libro_Rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionPrestamo.Libro')),
                ('usuario_Rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
